// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9qZYgrNRUHkNzw8hLk1MApANGvsW9b94',
    appId: '1:171820157807:web:0d016176c02b9a6508769a',
    messagingSenderId: '171820157807',
    projectId: 'diplom-4585',
    authDomain: 'diplom-4585.firebaseapp.com',
    storageBucket: 'diplom-4585.appspot.com',
    measurementId: 'G-JR2ND8Z8LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFglVhaEbMKFh7Ei3mn3hdgq3rNJs0Gk',
    appId: '1:171820157807:android:77c6a7c4f7c9f06108769a',
    messagingSenderId: '171820157807',
    projectId: 'diplom-4585',
    storageBucket: 'diplom-4585.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADBY1_9O3rcckGppUdUMUTXx5WSUnuQzs',
    appId: '1:171820157807:ios:7091387ff193910708769a',
    messagingSenderId: '171820157807',
    projectId: 'diplom-4585',
    storageBucket: 'diplom-4585.appspot.com',
    iosBundleId: 'com.example.dimplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADBY1_9O3rcckGppUdUMUTXx5WSUnuQzs',
    appId: '1:171820157807:ios:7091387ff193910708769a',
    messagingSenderId: '171820157807',
    projectId: 'diplom-4585',
    storageBucket: 'diplom-4585.appspot.com',
    iosBundleId: 'com.example.dimplom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9qZYgrNRUHkNzw8hLk1MApANGvsW9b94',
    appId: '1:171820157807:web:5fd7ebc8e442efaa08769a',
    messagingSenderId: '171820157807',
    projectId: 'diplom-4585',
    authDomain: 'diplom-4585.firebaseapp.com',
    storageBucket: 'diplom-4585.appspot.com',
    measurementId: 'G-R47QC2FWQW',
  );
}
